spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/koreadb?serverTimezone=Asia/Seoul
    username: korea
    password: korea1234
    
  jpa:
    hibernate:
      ddl-auto: create
